[package]
name = "omni-utils"
edition.workspace = true
version.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
near-sdk.workspace = true

omni-utils-derive.workspace = true

[dev-dependencies]
near-sandbox = { version = "0.3.11", features = ["generate", "singleton_cleanup"] }
near-api = "0.8.6"
cargo-near-build = { version = "0.11.3", features = ["build_internal"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json.workspace = true
